version: '3'

services:
  app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  fastapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000