version: '3'

services:
  # nuxt:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   container_name: nuxt
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./nuxt:/app/
  #     - /app/node_modules
  # app:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   image: node-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development


  # fastapi:
  #   build:
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   container_name: fastapi
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000