version: "3"
services:
  backend:
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/code
      - static:/code/static_root
      - media:/code/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - AXIOS_BASEURL=http://backend:8000/api
        - AXIOS_BROWSER_BASEURL=/api
    expose:
      - "3000"
    command: "npm run start"
    environment:
      - AXIOS_BASEURL=http://backend:8000/api
      - AXIOS_BROWSER_BASEURL=/api